### PR TITLE
Column search ui

### PR DESCRIPTION
**Pull request by bbenne10**
As mentioned in #1, it's REALLY basic. I'm thinking about two additional features: the ability to specify percentage-based widths and the ability to have a column fill space. This should start discussion well enough though.

Commit 93781ac isn't REALLY necessary for this feature, but I was getting errors when using the google code repository for gcfg and this commit works around that.

### CODE REVIEW

**Comment by laochailan** [comment]
That looks nice. Making the order of columns variable would be nice, too. Having the Subject first adds a lot of empty space to the layout.

Your other ideas sound good, too. Maybe we can squeeze all of this in the width option:

width >= 1: width in characters
0 <= width < 1: width as a percentage
width < 0: fill space

**Comment by bbenne10** [comment]
This seems more preferrable to me:

width >= 1: width in chars
0 < width < 1: width as a percentage
<=0: fill

I'll update this sometime soon...I've gotten a little feature happy and am currently implementing line highlighting for unread mail...

**Comment by bbenne10** [comment]
With regard to changing the order of the columns: Sure. The current one just replicates my preferences. We can discuss either a better ordering or an option to configure them to a users liking.

**Comment by laochailan** [comment]
The problem with <=0 is that someone might want to disable a column. The only way to do this then is to use a very small fraction.

Isn’t the unread tag in the tag column enough of a highlight? I have a shortcut search for unread messages and having every line in that search highlighted would look a bit silly. What about just displaying the unread tag in the tag column in a bright color?

This could be implemented very cleanly by extending the tag aliasing feature so you can specify a color. Additionally, users can highlight custom tags like “attachment” or “important” if they like with that feature.

**Comment by bbenne10** [comment]
Sure. I'll work on getting percentage and fill implemented. Assuming you intend to merge, do you want to merge this now and I can finish up that work in another PR? Or would you prefer the whole thing together?

**Comment by laochailan** [comment]
I would prefer the whole thing together. Thanks.

**Comment by bbenne10** [comment]
I'll rebase these changes onto current master (to deal with the tag highlighting conflicts) and then get to work on the rest of the features for this, probably with the ability to modify the order too sometime this coming week. Thanks for being so open to some feature creep :)

**Comment by laochailan** [comment]
Great :) It’s not like barely has too many features. Many parts are very spartanic because of my laziness. e.g. have you tried replying to a mail with multiple receivers? It tries to do something very funny in that case.

But I’m motivated now. This morning I added some basic file path tab completion to the prompt so you can choose attachments more easily.

**Comment by bbenne10** [comment]
Okay. With the last push, we have everything but "fill" columns. Still need to mentally work out how I should handle those.

**Comment by bbenne10** [comment]
Or not. Just discovered some weird bugs. I'll work those out soon.

**Comment by laochailan** [comment]
Cool, I’ve just looked over the changes. Are you sure you want to have the part width calculation and truncation in a single function? Maybe some

`fixedPartWidth(partWidth float64) int`

function returning the fixed part width for an arbitrary config float64 part width would be better. Because I saw the float64 type bleeding out in all kinds of variables.

About the fill columns: what about calculating all other widths first and then setting each fill column width to
`fillWidth = (terminalWidth-sum(otherWidths))/numberOfFillColumns`?

Then again, my fixedPartWidth function should rather be

`fixedPartWidths(partWidths []float64) []int`

so it can handle all the widths at once and calculate/set the fill column widths.

But those are just first glance suggestions. Happy hacking!

**Comment by bbenne10** [comment]
I've recently run out of time to work on this actively. I'll reopen when I get the feature sorted out properly (including fill columns)

**Pull request closed without merging**
